### ISSUE TITLE
javax.servlet.ServletContainerInitializer class cast issues when running standalone client

### ISSUE THREAD

**Issue by ianwdunlop** [AtomGraph/Web-Client#44]
Tomcat: 8.0.5
Java: 1.8.0_05
OS: Mac OSX 10.8.5
After mvn install graphity-ldp then graphity-browser

Deploy war graphity-browser/target/client-1.0.12-SNAPSHOT.war
Starting webapp gives:
org.apache.catalina.startup.ContextConfig.processServletContainerInitializers Failed to process JAR found at URL [/graphity] for ServletContainerInitializers for context with name [{1}]
 java.io.IOException: java.lang.ClassCastException: Cannot cast com.sun.jersey.server.impl.container.servlet.JerseyServletContainerInitializer to javax.servlet.ServletContainerInitializer

**Comment by pumba-lt** [comment]
If someone is having this issue, please try building the project with `mvn -Pstandalone package` (should produce a `.war`). That is what NetBeans does and works fine for me.

**Comment by namedgraph** [comment]
@ianwdunlop would be awesome if you could give https://hub.docker.com/r/atomgraph/web-client a try :)
