### ISSUE TITLE
Tomcat deployment for release 1.1.2

### ISSUE THREAD

**Issue by Bric-e** [AtomGraph/Web-Client#59]
Hello, 

Once i have generated the .war file to deploy client-1.1.2 I have been encountered 2 issues on Tomcat : 
- From Tomcat 6, CSS was not applied,
- From tomcat 7, it was ok but I have needed to add -XX:MaxPermSize=256m to JVM options.

That is not a really big issue, but it could help newbie people if documentation would be updated. 

BR, 

Brice

**Comment by pumba-lt** [comment]
These are good points. I think Tomcat 7 is preferred as I know it has a (new?) default servlet which serves static content. It is configured in web.xml. Could that be the issue with CSS?

Here are my Tomcat options:
`-XX:PermSize=256m -XX:MaxPermSize=256m -Dorg.apache.tomcat.util.buf.UDecoder.ALLOW_ENCODED_SLASH=true`

**Comment by namedgraph** [comment]
We have released a Docker image: https://hub.docker.com/r/atomgraph/web-client
See if it that solves the issue.
