### ISSUE TITLE
Error running RDFXML2SVG.xsl from the command line

### ISSUE THREAD

**Issue by diptenduLF** [AtomGraph/Web-Client#73]
I tried the command 

java -cp saxon9he.jar net.sf.saxon.Transform -t -s:test.xml -xsl:RDFXML2SVG.xsl -o:out.svg

and got the error

Saxon-HE 9.9.1.7J from Saxonica
Java version 1.8.0_144
Static error in {math:random()} in expression in xsl:sequence/@select on line 90 column 112 of RDFXML2SVG.xsl:
  XPST0017: Cannot find a 0-argument function named Q{http://exslt.org/math}random()
Static error in {math:abs($number)} in expression in xsl:sequence/@select on line 98 column 116 of RDFXML2SVG.xsl:
  XPST0017: Cannot find a 1-argument function named Q{http://exslt.org/math}abs()
Static error in {math:sqrt($number)} in expression in xsl:sequence/@select on line 106 column 117 of RDFXML2SVG.xsl:
  XPST0017: Cannot find a 1-argument function named Q{http://exslt.org/math}sqrt()
Errors were reported during stylesheet compilation

**Comment by namedgraph** [comment]
Hmm something must have changed in Saxon's support of EXSLT...

Can you try with version 9.1.0.8, which is what Web-Client is using?
https://sourceforge.net/projects/saxon/files/Saxon-B/9.1.0.8/

**Comment by diptenduLF** [comment]
Yes it works with the older version but this is what I get.

[image: image.png]

As you can see this is not of much use. How can I visualise the triples
Subject --> Predicate  --> Object ?

Regards,

Diptendu Dutta

**Comment by namedgraph** [comment]
Cannot see the image unfortunately. Can you upload it somewhere else?

And may I see the RDF/XML file? Or a portion of it. If so, please put it on Gist or upload it somewhere.

**Comment by diptenduLF** [comment]
I have attached the screenshot with this email.

The RDF is given below:

<rdf:RDF
    xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
    xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#">
  <rdf:Description>
    <rdf:subject rdf:parseType="Resource">
      <rdfs:label>TheConsignor</rdfs:label>
    </rdf:subject>
    <rdf:predicate rdf:resource="http://www.lke.com/lke.owl#shall%20deliver
"/>
    <rdf:object rdf:parseType="Resource">
      <rdfs:label>theConsignedUnits</rdfs:label>
    </rdf:object>
  </rdf:Description>
  <rdf:Description>
    <rdf:subject rdf:parseType="Resource">
      <rdfs:label>rulesofinterpretation</rdfs:label>
    </rdf:subject>
    <rdf:predicate rdf:resource="http://www.lke.com/lke.owl#apply%20in"/>
    <rdf:object rdf:parseType="Resource">
      <rdfs:label>thisConsignmentAgreement</rdfs:label>
    </rdf:object>
  </rdf:Description>
.
.
</rdf:RDF>

**Comment by namedgraph** [comment]
Attachements are not coming through here.

This is some weird RDF/XML. Is it from Jena?

The stylesheet will not support just any RDF/XML, it is tailored for Jena's RDF/XML:
https://jena.apache.org/documentation/io/rdfxml_howto.html#rdfxml-rdfxml-abbrev

**Comment by diptenduLF** [comment]
You can see the image at  https://ibb.co/ygbTy0c

The RDF was generated using the "RDF/XML" format in Apache Jena

Should I use the "RDF/XML-ABBREV"format?

**Comment by namedgraph** [comment]
Yes, please try `RDF/XML-ABBREV`.

**Comment by namedgraph** [comment]
@diptenduLF did it work?

**Comment by diptenduLF** [comment]
Not really.

The number of nodes is less (I guess due to the use of the RDF/XML-ABBREV
format) but the diagram is just a collection of nodes.

Please check https://ibb.co/s5jGx0W

Regards,

Diptendu Dutta

**Comment by namedgraph** [comment]
Could you upload the RDF/XML data somewhere?

**Comment by diptenduLF** [comment]
I am including it inline since attachments are not going thru

<rdf:RDF
    xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
    xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#">
  <rdf:Description>
    <rdf:subject>
      <rdf:Description rdf:nodeID="A0">
        <rdfs:label>Consignor</rdfs:label>
      </rdf:Description>
    </rdf:subject>
    <rdf:predicate rdf:resource="
http://www.aunwesha.com/lke.owl#accepted%20by"/>
    <rdf:object rdf:parseType="Resource">
      <rdfs:label>consignee</rdfs:label>
    </rdf:object>
  </rdf:Description>
  <rdf:Description>
    <rdf:subject>
      <rdf:Description rdf:nodeID="A1">
        <rdfs:label>Consignee</rdfs:label>
      </rdf:Description>
    </rdf:subject>
    <rdf:predicate rdf:resource="
http://www.aunwesha.com/lke.owl#shall%20assist%20in"/>
    <rdf:object rdf:parseType="Resource">
      <rdfs:label>protection of such Intellectual Property
Rights</rdfs:label>
    </rdf:object>
  </rdf:Description>
  <rdf:Description>
    <rdf:subject rdf:parseType="Resource">
      <rdfs:label>it</rdfs:label>
    </rdf:subject>
    <rdf:predicate rdf:resource="
http://www.aunwesha.com/lke.owl#complied%20with"/>
    <rdf:object rdf:parseType="Resource">
      <rdfs:label>requirement</rdfs:label>
    </rdf:object>
  </rdf:Description>
  <rdf:Description>
    <rdf:subject rdf:nodeID="A1"/>
    <rdf:predicate rdf:resource="
http://www.aunwesha.com/lke.owl#shall%20pay%20invoices%20in"/>
    <rdf:object rdf:parseType="Resource">
      <rdfs:label>15 days</rdfs:label>
    </rdf:object>
  </rdf:Description>
  <rdf:Description>
    <rdf:subject>
      <rdf:Description rdf:nodeID="A2">
        <rdfs:label>Party</rdfs:label>
      </rdf:Description>
    </rdf:subject>
    <rdf:predicate rdf:resource="http://www.aunwesha.com/lke.owl#begins"/>
    <rdf:object rdf:parseType="Resource">
      <rdfs:label>negotiations</rdfs:label>
    </rdf:object>
  </rdf:Description>
  <rdf:Description>
    <rdf:subject rdf:parseType="Resource">
      <rdfs:label>administrator</rdfs:label>
    </rdf:subject>
    <rdf:predicate rdf:resource="http://www.aunwesha.com/lke.owl#is"/>
    <rdf:object rdf:parseType="Resource">
      <rdfs:label>appointed</rdfs:label>
    </rdf:object>
  </rdf:Description>
  <rdf:Description>
    <rdf:subject rdf:parseType="Resource">
      <rdfs:label>CONSIGNMENT AGREEMENT</rdfs:label>
    </rdf:subject>
    <rdf:predicate rdf:resource="http://www.aunwesha.com/lke.owl#is"/>
    <rdf:object rdf:parseType="Resource">
      <rdfs:label>dated</rdfs:label>
    </rdf:object>
  </rdf:Description>
  <rdf:Description>
    <rdf:subject rdf:nodeID="A2"/>
    <rdf:predicate rdf:resource="http://www.aunwesha.com/lke.owl#has"/>
    <rdf:object rdf:parseType="Resource">
      <rdfs:label>liability for 10.2.1</rdfs:label>
    </rdf:object>
  </rdf:Description>
  <rdf:Description>
    <rdf:subject rdf:parseType="Resource">
      <rdfs:label>by control</rdfs:label>
    </rdf:subject>
    <rdf:predicate rdf:resource="http://www.aunwesha.com/lke.owl#with"/>
    <rdf:object rdf:nodeID="A2"/>
  </rdf:Description>
  <rdf:Description>
    <rdf:subject rdf:nodeID="A2"/>
    <rdf:predicate rdf:resource="http://www.aunwesha.com/lke.owl#threatens
"/>
    <rdf:object rdf:parseType="Resource">
      <rdfs:label>cease</rdfs:label>
    </rdf:object>
  </rdf:Description>
  <rdf:Description>
    <rdf:subject rdf:nodeID="A0"/>
    <rdf:predicate rdf:resource="
http://www.aunwesha.com/lke.owl#shall%20deliver"/>
    <rdf:object rdf:parseType="Resource">
      <rdfs:label>Consigned Units</rdfs:label>
    </rdf:object>
  </rdf:Description>
  <rdf:Description>
    <rdf:subject rdf:parseType="Resource">
      <rdfs:label>MAXIMUM CONSIGNMENT PERIOD 7.1 Maximum period
consignee</rdfs:label>
    </rdf:subject>
    <rdf:predicate rdf:resource="
http://www.aunwesha.com/lke.owl#can%20hold%20goods%20under"/>
    <rdf:object rdf:parseType="Resource">
      <rdfs:label>agreement</rdfs:label>
    </rdf:object>
  </rdf:Description>
  <rdf:Description>
    <rdf:subject rdf:nodeID="A2"/>
    <rdf:predicate rdf:resource="http://www.aunwesha.com/lke.owl#threatens
"/>
    <rdf:object>
      <rdf:Description rdf:nodeID="A3">
        <rdfs:label>suspend</rdfs:label>
      </rdf:Description>
    </rdf:object>
  </rdf:Description>
  <rdf:Description>
    <rdf:subject rdf:nodeID="A2"/>
    <rdf:predicate rdf:resource="http://www.aunwesha.com/lke.owl#threatens
"/>
    <rdf:object rdf:nodeID="A3"/>
  </rdf:Description>
  <rdf:Description>
    <rdf:subject rdf:parseType="Resource">
      <rdfs:label>connection</rdfs:label>
    </rdf:subject>
    <rdf:predicate rdf:resource="http://www.aunwesha.com/lke.owl#with"/>
    <rdf:object>
      <rdf:Description rdf:nodeID="A4">
        <rdfs:label>Consignment Agreement</rdfs:label>
      </rdf:Description>
    </rdf:object>
  </rdf:Description>
  <rdf:Description>
    <rdf:subject>
      <rdf:Description rdf:nodeID="A5">
        <rdfs:label>OEM</rdfs:label>
      </rdf:Description>
    </rdf:subject>
    <rdf:predicate rdf:resource="http://www.aunwesha.com/lke.owl#has"/>
    <rdf:object rdf:parseType="Resource">
      <rdfs:label>Intellectual Property Rights</rdfs:label>
    </rdf:object>
  </rdf:Description>
  <rdf:Description>
    <rdf:subject rdf:parseType="Resource">
      <rdfs:label>part-provision</rdfs:label>
    </rdf:subject>
    <rdf:predicate rdf:resource="http://www.aunwesha.com/lke.owl#becomes"/>
    <rdf:object rdf:parseType="Resource">
      <rdfs:label>invalid</rdfs:label>
    </rdf:object>
  </rdf:Description>
  <rdf:Description>
    <rdf:subject rdf:parseType="Resource">
      <rdfs:label>other Party</rdfs:label>
    </rdf:subject>
    <rdf:predicate rdf:resource="http://www.aunwesha.com/lke.owl#commits"/>
    <rdf:object rdf:parseType="Resource">
      <rdfs:label>breach of other term of Consignment Agreement</rdfs:label>
    </rdf:object>
  </rdf:Description>
  <rdf:Description>
    <rdf:subject rdf:nodeID="A1"/>
    <rdf:predicate rdf:resource="http://www.aunwesha.com/lke.owl#has"/>
    <rdf:object rdf:parseType="Resource">
      <rdfs:label>Obligations</rdfs:label>
    </rdf:object>
  </rdf:Description>
  <rdf:Description>
    <rdf:subject rdf:nodeID="A0"/>
    <rdf:predicate rdf:resource="http://www.aunwesha.com/lke.owl#is"/>
    <rdf:object rdf:parseType="Resource">
      <rdfs:label>willing</rdfs:label>
    </rdf:object>
  </rdf:Description>
  <rdf:Description>
    <rdf:subject rdf:nodeID="A5"/>
    <rdf:predicate rdf:resource="http://www.aunwesha.com/lke.owl#has"/>
    <rdf:object rdf:parseType="Resource">
      <rdfs:label>obligation</rdfs:label>
    </rdf:object>
  </rdf:Description>
  <rdf:Description>
    <rdf:subject rdf:nodeID="A1"/>
    <rdf:predicate rdf:resource="http://www.aunwesha.com/lke.owl#shall%20On
"/>
    <rdf:object rdf:parseType="Resource">
      <rdfs:label>termination of Consignment Agreement</rdfs:label>
    </rdf:object>
  </rdf:Description>
  <rdf:Description>
    <rdf:subject rdf:parseType="Resource">
      <rdfs:label>petition</rdfs:label>
    </rdf:subject>
    <rdf:predicate rdf:resource="http://www.aunwesha.com/lke.owl#is"/>
    <rdf:object rdf:parseType="Resource">
      <rdfs:label>filed</rdfs:label>
    </rdf:object>
  </rdf:Description>
  <rdf:Description>
    <rdf:subject rdf:nodeID="A4"/>
    <rdf:predicate rdf:resource="http://www.aunwesha.com/lke.owl#shall"/>
    <rdf:object rdf:parseType="Resource">
      <rdfs:label>shall governed</rdfs:label>
    </rdf:object>
  </rdf:Description>
  <rdf:Description>
    <rdf:subject rdf:parseType="Resource">
      <rdfs:label>Nothing</rdfs:label>
    </rdf:subject>
    <rdf:predicate rdf:resource="http://www.aunwesha.com/lke.owl#in"/>
    <rdf:object rdf:nodeID="A4"/>
  </rdf:Description>
  <rdf:Description>
    <rdf:subject rdf:nodeID="A0"/>
    <rdf:predicate rdf:resource="http://www.aunwesha.com/lke.owl#is%20in"/>
    <rdf:object rdf:parseType="Resource">
      <rdfs:label>business of marketing</rdfs:label>
    </rdf:object>
  </rdf:Description>
  <rdf:Description>
    <rdf:subject rdf:parseType="Resource">
      <rdfs:label>death</rdfs:label>
    </rdf:subject>
    <rdf:predicate rdf:resource="http://www.aunwesha.com/lke.owl#caused%20by
"/>
    <rdf:object rdf:parseType="Resource">
      <rdfs:label>its negligence</rdfs:label>
    </rdf:object>
  </rdf:Description>
  <rdf:Description>
    <rdf:subject rdf:nodeID="A0"/>
    <rdf:predicate rdf:resource="
http://www.aunwesha.com/lke.owl#shall%20provide%20Consignee%20with"/>
    <rdf:object rdf:parseType="Resource">
      <rdfs:label>sale invoice</rdfs:label>
    </rdf:object>
  </rdf:Description>
  <rdf:Description>
    <rdf:subject rdf:parseType="Resource">
      <rdfs:label>rules</rdfs:label>
    </rdf:subject>
    <rdf:predicate rdf:resource="http://www.aunwesha.com/lke.owl#apply%20in
"/>
    <rdf:object rdf:nodeID="A4"/>
  </rdf:Description>
  <rdf:Description>
    <rdf:subject rdf:parseType="Resource">
      <rdfs:label>claim</rdfs:label>
    </rdf:subject>
    <rdf:predicate rdf:resource="http://www.aunwesha.com/lke.owl#in"/>
    <rdf:object rdf:parseType="Resource">
      <rdfs:label>respect of breach of Consignment Agreement</rdfs:label>
    </rdf:object>
  </rdf:Description>
  <rdf:Description>
    <rdf:subject rdf:nodeID="A1"/>
    <rdf:predicate rdf:resource="http://www.aunwesha.com/lke.owl#consume"/>
    <rdf:object rdf:parseType="Resource">
      <rdfs:label>units in Pilot project</rdfs:label>
    </rdf:object>
  </rdf:Description>
  <rdf:Description>
    <rdf:subject rdf:parseType="Resource">
      <rdfs:label>rights</rdfs:label>
    </rdf:subject>
    <rdf:predicate rdf:resource="http://www.aunwesha.com/lke.owl#in"/>
    <rdf:object rdf:parseType="Resource">
      <rdfs:label>designs</rdfs:label>
    </rdf:object>
  </rdf:Description>
  <rdf:Description>
    <rdf:subject rdf:nodeID="A1"/>
    <rdf:predicate rdf:resource="
http://www.aunwesha.com/lke.owl#shall%20purchase%20Consigned%20Units%20at"/>
    <rdf:object rdf:parseType="Resource">
      <rdfs:label>prices</rdfs:label>
    </rdf:object>
  </rdf:Description>
  <rdf:Description>
    <rdf:subject rdf:nodeID="A1"/>
    <rdf:predicate rdf:resource="
http://www.aunwesha.com/lke.owl#shall%20promptly%20notify"/>
    <rdf:object rdf:nodeID="A5"/>
  </rdf:Description>
  <rdf:Description>
    <rdf:subject rdf:nodeID="A5"/>
    <rdf:predicate rdf:resource="
http://www.aunwesha.com/lke.owl#&apos;s%20Information"/>
    <rdf:object rdf:parseType="Resource">
      <rdfs:label>Documentation</rdfs:label>
    </rdf:object>
  </rdf:Description>
  <rdf:Description>
    <rdf:subject rdf:parseType="Resource">
      <rdfs:label>Inflow Technologies Pvt Ltd</rdfs:label>
    </rdf:subject>
    <rdf:predicate rdf:resource="
http://www.aunwesha.com/lke.owl#registered%20in"/>
    <rdf:object rdf:parseType="Resource">
      <rdfs:label>India</rdfs:label>
    </rdf:object>
  </rdf:Description>
  <rdf:Description>
    <rdf:subject rdf:nodeID="A1"/>
    <rdf:predicate rdf:resource="http://www.aunwesha.com/lke.owl#consume"/>
    <rdf:object rdf:parseType="Resource">
      <rdfs:label>units</rdfs:label>
    </rdf:object>
  </rdf:Description>
  <rdf:Description>
    <rdf:subject rdf:nodeID="A1"/>
    <rdf:predicate rdf:resource="
http://www.aunwesha.com/lke.owl#shall%20furnish%20monthly/Quarterly%20statement%20to
"/>
    <rdf:object rdf:nodeID="A0"/>
  </rdf:Description>
</rdf:RDF>

**Comment by diptenduLF** [comment]
Hello Martynas,

Were you able to find anything wrong in the RDF/XML?

Regards,

Diptendu Dutta

**Comment by namedgraph** [comment]
Sorry, not yet... I'm planning to look at it, but can't give you any timeline.

**Comment by namedgraph** [comment]
@diptenduLF would you be able to try again? There have been some changes/optimizations to the SVG graph stylesheet.

Looking at the RDF/XML example, `rdf:parseType="Resource"` is not supported. If you'd run your file through Jena's `riot` parser utility and produced `RDFXML_PLAIN`, there would be a higher chance of your data rendering correctly.
