### ISSUE TITLE
Using Web-Client with Apache Jena

### ISSUE THREAD

**Issue by kubajal** [AtomGraph/Web-Client#77]
Hello,
is it possible to use Web-Client together with Apache Jena as RDF triplestore on the backend?
To be more precise, I'd like to:
 1. use the [Docker image of Web-Client](https://hub.docker.com/r/atomgraph/web-client/)
 2. run Apache Jena separately with my custom RDF data loaded
 3. hook Web-Client into Apache Jena and use it as a browser for the RDF data loaded in Jena

I was looking at the [wiki](https://github.com/AtomGraph/Web-Client/wiki) but couldn't find any info on that, in particular how to configure the address+port of Jena in Web-Client. Is it even possible?
Thanks!

Best regards,
Jakub

**Comment by namedgraph** [comment]
Hi @kubajal. Sorry I missed this ticket...

You can browse any RDF resource including `DESCRIBE` and `CONSTRUCT` SPARQL query results.
However where the links will lead you depends on the URIs used in the dataset. If they do not dereference then it's not Linked Data and Web-Client will not be able to open them.

What we do is use the [Processor](https://github.com/AtomGraph/Processor) to publish Linked Data from a SPARQL endpoint such as Fuseki, and then use Web-Client to connect to the Processor instance.

I hope this helps.
